export const CONNECTION_SCREEN = 'ConnectionScreen'
export const HOME_SCREEN = 'HomeScreen'
export const BROWSE_SONGS_SCREEN = 'BrowseSongsScreen'
export const SEARCH_SONGS_SCREEN = 'SearchSongsScreen'
export const PLAYLIST_SCREEN = 'PlaylistScreen'
export const MAIN_SCREEN_CONTAINER = 'MainScreenContainer'
export const MAIN_SCREEN = 'MainScreen'
export const BROWSE_GROUPS_SCREEN = 'BrowseGroupsScreen'
